name: Hello World

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs: 
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello World!"
          - name: Run date
            run: date
    list:
        runs-on: ubuntu-latest
        steps:
          - name: list files and directories
            run: ls -l 
    testing_skip:
        runs-on: ubuntu-latest
        if: ${{!contains(join(github.event.commits.*.message, ''), '#skip')}}
        steps:
          - name: it will skip this job
            run: echo 'se imprime porque no hay slip'