name: Development pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize, closed]


jobs:
    simple_deployment_pipeline:
        if: |
          github.event_name == 'pull_request' &&
          (github.event.action == 'opened' ||
           github.event.action == 'synchronize' ||
           github.event.pull_request.state == 'open')
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v6
          - uses: actions/setup-node@v6
            with:
                node-version: '24'
          - name: Install dependencies
            run: npm install
          - name: Check style
            run: npm run eslint
          - name: run tests
            run: npm run test
          - name: build app
            run: npm run build
    tag_release:
        needs: [simple_deployment_pipeline]
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v6
            with:
              ref: ${{github.event.pull_request.merge_commit_sha}}
              fetch-depth: 0
          - name: Bump version and push tag
            uses:  anothrNick/github-tag-action@1.75.0
            env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              TAG_PREFIX: v
              PRERELEASE: true
