name: Bump version tagging
on:
    pull_request:
        branches: [main]
        types: [closed]

jobs:
    taging:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
        - uses: actions/checkout@v6
          with:
            ref: ${{github.event.pull_request.merge_commit_sha}}
            fetch-depth: 0
        - name: Add tag
          uses: anothrNick/github-tag-action@1.75.0
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            TAG_PREFIX: v

